fix(github): Github Action 내에서 SSH 소켓파일이 이미 존재하는 경우에 대한 버그 수정
- 에러 분석을 위한 로깅 명령어 추가 (set -x)
- 소켓 파일이 열려있는 경우에 대한 버그 수정
- `env.sh` 에 데이터를 넣는 순서 변경하여 버그 수정

diff --git a/.github/workflows/backend-cd.yml b/.github/workflows/backend-cd.yml
--- a/.github/workflows/backend-cd.yml
+++ b/.github/workflows/backend-cd.yml
@@ -35,15 +35,21 @@ jobs:
         env:
           SSH_AUTH_SOCK: /tmp/ssh_agent.sock
         run: |
+          set -x
           mkdir -p ~/.ssh
+          chmod 700 ~/.ssh
+          
+          rm -f $SSH_AUTH_SOCK
           ssh-agent -a $SSH_AUTH_SOCK > /dev/null
-          echo "${{ secrets.EC2_SSH_KEY }}" | ssh-add -
+          
+          echo "${{ secrets.EC2_SSH_KEY }}" | tr -d '\r' | ssh-add - || { echo "SSH Key Add Failed"; exit 1; }
+          
           ssh-keyscan -H -p ${{ secrets.EC2_PORT }} ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
           
+          echo "export DB_URL='${{ secrets.DB_URL }}'" > env.sh
           echo "export JPA_DDL_AUTO='${{ vars.JPA_DDL_AUTO }}'" >> env.sh
           echo "export LOG_PATH='${{ secrets.LOG_PATH }}'" >> env.sh
           echo "export LOG_LEVEL='${{ vars.LOG_LEVEL }}'" >> env.sh
-          echo "export DB_URL='${{ secrets.DB_URL }}'" > env.sh
           echo "export DB_USER='${{ secrets.DB_USER }}'" >> env.sh
           echo "export DB_PASSWORD='${{ secrets.DB_PASSWORD }}'" >> env.sh
           
